spring.application.name=Microservicio Spring Boot Core de Tienda Online
spring.datasource.initialize=false
spring.datasource.url=
spring.datasource.driver-class-name=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration